### ISSUE TITLE
PEP8ify the code

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/nchelpers#15]
There are a lot of PEP8 violations in this code base, mostly long lines. I've enabled flake8 (a Python linter) on Travis in [this branch](https://github.com/pacificclimate/nchelpers/tree/feature/flake8) so that we can try and address any of the problems that it points out. FWIW, [autopep8](https://pypi.python.org/pypi/autopep8) may fix all of the long lines for us.

**Comment by rod-glover** [comment]
Hmm. Most of those long lines are URLs in comments pointing at reference info. And there are a whack of minor violations in the form of 1 space instead of 2 before some inline comments.

Nonetheless, my bad, and apologies. My IDE points them out, but it doesn't scream about them.

**Comment by rod-glover** [comment]
Fixed in commit 3815085da0984bbce58db958e165776067517044
