### ISSUE TITLE
Make identification of climatological bounds / multi-year mean more flexible

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/nchelpers#22]
Currently: 

- A multi-year mean file is identified by having a climatology bounds variable, identified on the time variable by the attribute 'climatology', that exists

Improvements:

- Add a strict-mode flag to relevant functions (climatology_bounds_var_name, is_multi_year_mean, others?) that defaults to False (non-strict)
- In strict mode: use current rule
- In non-strict mode (in order of likelihood of correctness): 
  - _climatology bounds variable_ is identified by the following heuristics:
    - time variable has 'climatology' attribute (current case): use it
    - variable with name 'climatology_bounds', 'climatology_bnds', 'climo_bounds', 'climo_bnds' exists, even if it not identified by `time:climatology`
    - time variable has 'bounds' (not 'climatology') attribute identifying an existing variable AND that time bounds variable brackets multi-year periods (corresponding to the climatological averaging)
     - variable with name 'time_bounds' or 'time_bnds' exists (not identified by time:bounds) AND that time bounds variable brackets multi-year periods (corresponding to the climatological averaging)
  - _multi-year mean_ is identified by the following heuristics:
    - climatology bounds variable identified and exists as above
    - time variable has "suspicious" length: 1, 4, 12, 5, 13, 16, 17 (yearly, seasonal, monthly, and various concatenations) AND time variable has likely values (mid-month, mid-season, mid-year)

**Comment by rod-glover** [comment]
Unfortunately, adding the strict-mode flag (as a kw arg) will make `climatology_bounds_var_name`, `is_multi_year_mean` not be properties, which is a breaking change.

This can be restored by [separating the property from the property getter function](https://stackoverflow.com/a/5718537/1858846). Not entirely sure this is a good idea, but it would prevent existing code from breaking.

**Comment by jameshiebert** [comment]
What if the strict-mode was implemented as a property of the ``CFMetadata`` class that you can set on instantiation? Kind of like opening a file in read/write mode (and then it affects what you can do with the file later on).

**Comment by rod-glover** [comment]
I thought about that. It is less flexible, but it would certainly work. At the moment, I have a solution that preserves both properties and the option to call it with the strict parameter (albeit by a different but related name). I'll continue with that and we can refactor to the global flag later if we wish.

**Comment by rod-glover** [comment]
Note: Decided to make it a parameter of `CFMetadata` class constructor.
